# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: AKSDeployment
  vmImage: 'GpuSelfHostedAgent'

steps:
- script: echo Hello, AKSDeployment!
  displayName: 'Run a one-line script'

- bash: |
      source /usr/share/miniconda/etc/profile.d/conda.sh
      which conda
      cd Keras_Tensorflow
      conda env create -f tutorial_env.yml
      conda activate tutorial_env
      conda env list  
     # echo Login Azure Account
     # az login -t $(sptenent) --service-principal -u $(spidentity) --password $(spsecret)
  displayName: '00_AML_Configuration.ipynb'

- bash: |
      source /usr/share/miniconda/etc/profile.d/conda.sh
      conda remove -n tutorial_env
      conda env list  
  displayName: 'Cleanup Task'
  condition: always()