# Conda environment specification. The dependencies defined in this file will
# be automatically provisioned for runs with userManagedDependencies=False.

# Details about the Conda environment file format:
# https://conda.io/docs/user-guide/tasks/manage-environments.html#create-env-file-manually

name: project_environment
dependencies:
  # The python interpreter version.
  # Currently Azure ML only supports 3.5.2 and later.
- python=3.6

- pip:
    # Required packages for AzureML execution, history, and data preparation.
  - --index-url https://azuremlsdktestpypi.azureedge.net/sdk-release/Preview/E7501C02541B433786111FE8E140CAA1
  - --extra-index-url https://pypi.python.org/simple
  - azureml-defaults
  - papermill==0.14.1
  - python-dotenv==0.9.0
  - Pillow==5.2.0
  - wget==3.2
  - aiohttp==3.3.2
  - toolz==0.9.0
  - tqdm==4.23.4
  - azure-cli==2.0.41
  - keras==2.2.0
- tensorflow
- tornado==4.5.3
