name: AKSDeploymentPytorch
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.6
  - nb_conda==2.2.0
  - tornado==4.5.3
  - pytorch 
  - pip:
    - papermill==0.14.1
    - python-dotenv==0.9.0
    - Pillow==5.2.0
    - wget==3.2
    - matplotlib==2.2.2
    - aiohttp==3.3.2
    - toolz==0.9.0
    - tqdm==4.23.4
    - torchvision
    - azure
    - azureml-sdk[notebooks]==0.1.68
    - azure-cli