name: deployment_aml
dependencies:
  # The python interpreter version.
  # Currently Azure ML only supports 3.5.2 and later.
- python=3.6
- nb_conda
- tornado
- cudatoolkit
- tensorflow-gpu
- urllib3
- pip:
    # Required packages for AzureML execution, history, and data preparation.
  - papermill
  - python-dotenv
  - Pillow
  - wget
  - matplotlib
  - toolz
  - tqdm
  - azure-cli
  - keras==2.2.0
  - azureml-sdk[notebooks, contrib]==1.0.57
  - locustio
  - prompt-toolkit
  - git+https://github.com/Microsoft/StatisticsTracker
  - PyOpenSSL
